config/routes.rb
Rails.application.routes.draw do
   root to: 'home#index'
  resources :users, only: [:index, :import] do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'

  def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
      User.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def import
    User.import(params[:file])
    redirect_to users_path, notice: 'CSV importado com sucesso'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div>
  Aplicativo de Cartões de Alimentação
</div>
<div>
  <h4> Importar o dado </h4>

  <%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar o arquivo CSV" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppCard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= flash[:notice] %> <br><br>

<tr>
  <th>Nome do Arquivo: </th>
  <td><%= Pathname.new('spec/fixtures/dados-19-07-2018.csv').basename  %></td>
</tr> <br><br>

<tr>
  <th>Total de Linhas do Arquivo: </th>
  <td><%= IO.readlines('spec/fixtures/dados-19-07-2018.csv').size - 1  %></td>
</tr> <br><br>

<table>
  <thead>
    <tr>
      <th>Nome Completo</th>
      <th>Email</th>
      <th>Token</th>
      <th>Data de Admissão</th>
      <th>Valor disponível no cartão</th>
    </tr>
  </thead>

<tbody>
  <% @users.each do |user| %>
  <tr>
    <td> <%= user.name %> <%= user.surname %> </td>
    <td> <%= user.email %> </td>
    <td> <%= user.token %> </td>
    <td> <%= user.admission_date %> </td>
    <td> <%= user.available_amount %> </td>
  </tr>
  <% end %>
</tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Nome Completo</th>
      <th>Email</th>
      <th>Token</th>
      <th>Data de Admissão</th>
      <th>Valor disponível no cartão</th>
    </tr>
  </thead>

<tbody>
  <% @users.each do |user| %>
  <tr>
    <td> <%= user.name %> <%= user.surname %> </td>
    <td> <%= user.email %> </td>
    <td> <%= user.token %> </td>
    <td> <%= user.admission_date %> </td>
    <td> <%= user.available_amount %> </td>
  </tr>
  <% end %>
</tbody>
</table>